# Generated by Django 6.0.3 on 2026-03-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('fun', 'Fun')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-spent_on', '-created_at'],
            },
        ),
    ]
