# Generated by Django 6.0.3 on 2026-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['spent_on', 'category'], name='expenses_ex_spent_o_23ddd5_idx'),
        ),
    ]
